WebUI/Pages/Browse/Index.cshtml.cs
using BusinessObjects.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Interfaces;
using WebUI.Binding;
using WebUI.Utils;

namespace WebUI.Pages.Browse
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public List<Book> Books { get; set; }

        private readonly IBookService bookService;
        private readonly IBorrowItemService borrowItemService;

        public IndexModel(IBookService bookService, IBorrowItemService borrowItemService)
        {
            this.bookService = bookService;
            this.borrowItemService = borrowItemService;
        }

        public void OnGet(ToastMessage? toastMessage)
        {
            Books = bookService.GetAllBooks();
            if (toastMessage != null && !string.IsNullOrEmpty(toastMessage.Title) && !string.IsNullOrEmpty(toastMessage.Message))
            {
                ViewData["ToastMessage"] = new List<ToastMessage>() { toastMessage };
            }
        }

        public IActionResult OnPostBorrow(int? id)
        {
            if (id == null)
            {
                return RedirectToPage("Errors/404");
            }
            Account? currentUser = HttpContext.Session.GetObjectFromJson<Account>(SessionUtils.LOGGED_IN_USER_KEY);
            if (currentUser == null)
            {
                return Forbid();
            }
            Book? book = bookService.GetBook((int)id);
            if (book == null)
            {
                return RedirectToPage("Errors/404");
            }

            var borrowedItems = borrowItemService.GetBorrowItemByAccountIdAndBookId(currentUser.Id, book.Id).Where(b => b.ReturnedDate == null).FirstOrDefault();
            if (borrowedItems != null && borrowedItems.ReturnedDate == null)
            {
                ToastMessage errorMessage = new()
                {
                    Title = "Error",
                    Message = $"You've already borrowed this book",
                    ToastType = ToastType.Error
                };

                return RedirectToAction("Index", errorMessage);
            }

            borrowItemService.BorrowBook(currentUser, book);

            ToastMessage toastMessage = new()
            {
                Title = "Succes",
                Message = $"You borrowed {book.Name}",
                ToastType = ToastType.Success
            };

            return RedirectToAction("Index", toastMessage);
        }
    }
}

WebUI/Pages/Browse/Index.cshtml
@page
@using WebUI.Binding
@model WebUI.Pages.Browse.IndexModel
@{
    ViewData["Title"] = "Discovery";
}
@if (ViewData["ToastMessage"] != null)
{
    List<ToastMessage> toasts = (List<ToastMessage>?)ViewData["ToastMessage"] ?? new();

    foreach(ToastMessage toast in toasts)
    {
        <div class="position-fixed bottom-0 right-0 p-3" style="z-index: 5; right: 0; bottom: 0;">
            <div id="liveToast" class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-delay="2000">
                <div class="toast-header">
                    <strong class="mr-auto text-@toast.ToastTypeString">@toast.Title</strong>
                    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="toast-body">
                    @toast.Message
                </div>
            </div>
        </div>
    }
}

<div class="card">
    <div class="card-header py-3">
        <div class="row w-100">
            <div class="col-10">
                <h3 class="m-0 font-weight-bold text-primary">Browse Library</h3>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Books[0].Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Books[0].Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Books[0].Isbn)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Books[0].PublishedDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Books[0].AuthorNavigation.Name)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Books)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Isbn)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PublishedDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AuthorNavigation.Name)
                            </td>
                            <td class="d-flex justify-content-around">
                                <a data-toggle="modal" data-target="#borrowModal" data-id="@item.Id" data-name="@item.Name" class="btn btn-success openBorrowModal">Borrow</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>

<!-- Delete Account Modal-->
<div class="modal fade" id="borrowModal" tabindex="-1" role="dialog" aria-labelledby="borrowBookModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="borrowBookModal">Borrow this book?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <h4>You want to borrow this book?</h4>
                <hr />
                <dl class="row">
                    <dt class="col-sm-2 ">Name</dt>
                    <dd class="col-sm-10 nameValue"></dd>
                </dl>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <form method="post" asp-page-handler="Borrow">
                    <input type="hidden" id="idValue" name="id" class="idValue" />
                    <button class="btn btn-success" type="submit">Borrow</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function (event) {
        console.log('event loaded');
        $(".openBorrowModal").click(function () {
            console.log(this);
            const id = $(this).data('id');
            const name = $(this).data('name');
            $('input.idValue').val(id);
            $('dd.nameValue').html(name);
        });
    });
</script>